# Generated by Django 5.0.1 on 2024-05-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
